### ISSUE TITLE
'CURL_ERROR: SSL certificate problem

### ISSUE THREAD

**Issue by sangnguyenplus** [THECALLR/sdk-php#10]
Hi TheCallr support team,
I just test your API. I followed your instruction in https://github.com/THECALLR/sdk-php but I getting below error. 
![capture](https://cloud.githubusercontent.com/assets/6972407/14179154/f241652a-f72b-11e5-8a90-1d13e412b28b.PNG)

This is my source code.
![code](https://cloud.githubusercontent.com/assets/6972407/14179140/e97613f0-f72b-11e5-9836-eda32bf5e591.PNG)

Please help me check it.
Thanks!

**Comment by pcedelle** [comment]
Hello,

All API calls in the SDK are made by cURL through HTTPS. Your problem is not related to the SDK but to your local cURL configuration; you are missing a local certificate needed for HTTPS requests.

[This answer](https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/replies/37017) on Laracasts seems to point to a solution to your problem.

Thank you
